-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE VIEW "public"."acl_library" AS
-- SELECT library.id,
--     agency_user.id AS user_id,
--     'read'::text AS access
--   FROM agency_user, agency, library
--   WHERE ((agency_user.agency_role = 'agency_admin')
--     AND (agency_user.agency_id = agency.id)
--     AND (agency.id = library.agency_id));
